version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
     dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "urllib3"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
     dependencies:
        patterns:
          - "*"
